version: "1"

services:
  backend:
    build: backend
    ports:
      - "1024:1024"
    volumes:
        - ./storage:/storage

  frontend:
    build: frontend
    depends_on:
      - backend
    ports:
      - "1025:1025"
    volumes:
      - ./storage:/storage
